import Head from "next/head";
import About from "@src/components/About";
import Contact from "@src/components/Contact";
import Projects from "@src/components/Projects";
import Skills from "@src/components/Skills";
import Main from "@src/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Katsumi | Fullstack developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
